services:
    db:
        image: postgres:17.5
        restart: unless-stopped
        profiles:
            - db
        environment:
            POSTGRES_USER: ${DB_USER:-admin}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
            POSTGRES_DB: drivelo
            TZ: Europe/Warsaw
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U appuser"]
            interval: 30s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: .
            dockerfile: ./.docker/backend/Dockerfile
        profiles:
            - backend
        depends_on:
            db: { condition: service_healthy }

    frontend:
        build:
            context: .
            dockerfile: ./.docker/frontend/Dockerfile
        profiles:
            - frontend

volumes:
    pgdata:
        driver: local