version: '3'

tasks:
    start-dev-db:
        cmds:
            - docker-compose -profile db up
        env:
            DB_USER: admin
            DB_PASSWORD: admin

    start-dev:
        cmds:
            - docker-compose -profile db,backend,frontend up
        env:
            DB_USER: admin
            DB_PASSWORD: admin